"""initial schema

Revision ID: 120fa3cbb54e
Revises: 
Create Date: 2026-03-01 18:06:00.150998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120fa3cbb54e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_interval', sa.String(), nullable=True),
    sa.Column('date_posted', sa.String(), nullable=True),
    sa.Column('date_scraped', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('job_url', sa.String(), nullable=True),
    sa.Column('apply_url', sa.String(), nullable=True),
    sa.Column('apply_type', sa.String(), nullable=True),
    sa.Column('ats_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('relevance_reason', sa.String(), nullable=True),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('role_type', sa.String(), nullable=True),
    sa.Column('years_experience_required', sa.Integer(), nullable=True),
    sa.Column('key_skills', sa.String(), nullable=True),
    sa.Column('red_flags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company', 'title', 'date_posted', name='uq_job')
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_term', sa.String(), nullable=True),
    sa.Column('ran_at', sa.DateTime(), nullable=True),
    sa.Column('results_found', sa.Integer(), nullable=True),
    sa.Column('results_kept', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_runs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
